### ISSUE TITLE
Users can see my pc hostname

### ISSUE THREAD

**Issue by skorotkiewicz** [josephernest/talktalktalk#17]
I have no idea how, but users can see my hostname but I never told anyone, and no one knows it!

How?!

EDIT: This is very dangerous messaging, you better not use it

**Comment by josephernest** [comment]
Can you explain your setup (which kind of server)? 
Which hostname is seen? Your hostname as client or as server?

> This is very dangerous messaging

You probably missed the goal of this project. It's just a small chat coded in < 200 lines of code. Don't expect it to be protected against malicious users, because, first, by design, there's no "registration" with login/password for usernames. If you're looking for this, there are thousands of other chat solutions.

The goal here is to be able to deploy a chat for a small team in 2 minutes.

**Comment by skorotkiewicz** [comment]
Everyone can see the hostname of users (clients), it is very interesting how?

**Comment by josephernest** [comment]
Source? 

Can you find my hostname here: http://185.164.138.19:7311/ ? I'm user `FindMyHostname`.
